services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    environment: ## define as var de ambientes do .env do container, vai servir quando mudarmos sqlite para outra banco q necessite hospedar.
      - DATABASE_URL=sqlite:///database.db